# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180215_1927'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kirrurl',
            managers=[
            ],
        ),
    ]
