# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20180215_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=250, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
